//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.07 at 06:00:18 PM CET 
//


package be.vdab.entities;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the be.vdab.entities package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Boeken_QNAME = new QName("http://www.vdab.be/boeken", "Boeken");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: be.vdab.entities
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Boeken }
     * 
     */
    public Boeken createBoeken() {
        return new Boeken();
    }

    /**
     * Create an instance of {@link Curriculums }
     * 
     */
    public Curriculums createCurriculums() {
        return new Curriculums();
    }

    /**
     * Create an instance of {@link Curriculum }
     * 
     */
    public Curriculum createCurriculum() {
        return new Curriculum();
    }

    /**
     * Create an instance of {@link Boek }
     * 
     */
    public Boek createBoek() {
        return new Boek();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boeken }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vdab.be/boeken", name = "Boeken")
    public JAXBElement<Boeken> createBoeken(Boeken value) {
        return new JAXBElement<Boeken>(_Boeken_QNAME, Boeken.class, null, value);
    }

}
